version: "3"

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www/
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
        ports:
            - "8076:80"
        environment:
            UPLOAD_LIMIT: 64M            
        depends_on:
            - app
        container_name: gorizontclub_nginx

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www/
        depends_on:
            - db
        container_name: gorizontclub_app

    db:
        image: mysql:8.0.31
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: gorizontclub
            MYSQL_ROOT_PASSWORD: root
            UPLOAD_LIMIT: 64M
        ports:
            - 8101:3306
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: gorizontclub_db
